apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark-history
  namespace: spark
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spark-history
  template:
    metadata:
      labels:
        app: spark-history
    spec:
      containers:
        - name: spark-history
          image: myrepo/spark:3.5.5
          command: ["./entrypoint.sh", "history"]
          envFrom:
            - configMapRef:
                name: spark-configmap
          ports:
            - containerPort: 18080
          volumeMounts:
            - name: spark-events
              mountPath: /mnt/nfs/spark-events
      volumes:
        - name: spark-events
          nfs:
            server: nfs-server.local
            path: /export/spark-events
