
volumes:
  certs:
    driver: local
  esdata:
    driver: local
  kibanadata:
    driver: local
  spark-logstash01:
    driver: local
  spark-filebeat01:
    driver: local

networks:
  default:
    name: elastic
    external: false

services:

  es01:
    build:
      context: .
      dockerfile: Dockerfile
    image: cert-es-base
    labels:
      co.elastic.logs/module: elasticsearch
    volumes:
      - esdata:/usr/share/elasticsearch/data
      - certs:/usr/share/elasticsearch/config/certs
      # only needed for debugging initializations
      #   docker exec -it <Container-ID> bash
      # or through the Docker Desktop console
      - ./init:/usr/share/elasticsearch/init
    ports:
      - ${ES_PORT}:9200
    environment:
      - node.name=es01
      - cluster.name=${CLUSTER_NAME}
      - discovery.type=single-node
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
      - bootstrap.memory_lock=true
      # Xpack must be rooted at /usr/share/elasticsearch/config, so start with certs/
      - xpack.security.enabled=true
      - xpack.security.http.ssl.enabled=true
      - xpack.security.http.ssl.key=certs/es01/es01.key
      - xpack.security.http.ssl.certificate=certs/es01/es01.crt
      - xpack.security.http.ssl.certificate_authorities=certs/ca/ca.crt
      - xpack.security.transport.ssl.enabled=true
      - xpack.security.transport.ssl.key=certs/es01/es01.key
      - xpack.security.transport.ssl.certificate=certs/es01/es01.crt
      - xpack.security.transport.ssl.certificate_authorities=certs/ca/ca.crt
      - xpack.security.transport.ssl.verification_mode=certificate
      - xpack.license.self_generated.type=${LICENSE}
    mem_limit: ${ES_MEM_LIMIT}
    ulimits:
      memlock:
        soft: -1
        hard: -1
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -s --cacert config/certs/ca/ca.crt https://localhost:9200 | grep -q 'missing authentication credentials'",
        ]
      interval: 10s
      timeout: 10s
      retries: 120


  init-kibana:
    image: cert-es-base
    volumes:
      - ./init:/usr/share/elasticsearch/init
      - certs:/usr/share/elasticsearch/config/certs
    command: bash -f ./init/init-kibana.sh 
    environment:
      # do we need any of this? Taken from logstash
      # - xpack.monitoring.enabled=false
      - ELASTIC_USER=elastic
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
      - ELASTIC_HOSTS=https://es01:9200}
      # dubious we need kibana here
      - KIBANA_PASSWORD=${KIBANA_PASSWORD}
    depends_on:
      es01:
        condition: service_healthy

  init-index:
    image: cert-es-base
    volumes:
      - ./init:/usr/share/elasticsearch/init
      - certs:/usr/share/elasticsearch/config/certs
    command: bash -f ./init/init-index.sh 
    environment:
      # do we need any of this? Taken from logstash
      # - xpack.monitoring.enabled=false
      - ELASTIC_USER=elastic
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
      - ELASTIC_HOSTS=https://es01:9200}
      # dubious we need kibana here
      - KIBANA_PASSWORD=${KIBANA_PASSWORD}
    depends_on:
      es01:
        condition: service_healthy

  kibana:
    depends_on:
      es01:
        condition: service_healthy
      init-kibana:
        condition: service_completed_successfully
    image: docker.elastic.co/kibana/kibana:${STACK_VERSION}
    labels:
      co.elastic.logs/module: kibana
    volumes:
      - certs:/usr/share/kibana/config/certs
      - kibanadata:/usr/share/kibana/data
    ports:
      - ${KIBANA_PORT}:5601
    environment:
      - SERVERNAME=kibana
      - ELASTICSEARCH_HOSTS=https://es01:9200
      - ELASTICSEARCH_USERNAME=kibana_system
      - ELASTICSEARCH_PASSWORD=${KIBANA_PASSWORD}
      - ELASTICSEARCH_SSL_CERTIFICATEAUTHORITIES=config/certs/ca/ca.crt
      - XPACK_SECURITY_ENCRYPTIONKEY=${ENCRYPTION_KEY}
      - XPACK_ENCRYPTEDSAVEDOBJECTS_ENCRYPTIONKEY=${ENCRYPTION_KEY}
      - XPACK_REPORTING_ENCRYPTIONKEY=${ENCRYPTION_KEY}
    mem_limit: ${KB_MEM_LIMIT}
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -s -I http://localhost:5601 | grep -q 'HTTP/1.1 302 Found'",
        ]
      interval: 10s
      timeout: 10s
      retries: 120    
# mine

  spark-logstash01:
    depends_on:
      es01:
        condition: service_healthy
      init-index:
        condition: service_completed_successfully
    image: docker.elastic.co/logstash/logstash:${STACK_VERSION}    
    container_name: spark-logstash01
    labels:
      co.elastic.logs/module: logstash
    user: root
    ports: 
        - "${SPARK_LS_PORT}:${SPARK_LS_PORT}"
        - "9600:9600"
    volumes:
      - "certs:/usr/share/logstash/certs"
      # - "./logstash/pipeline/logstash.conf:/usr/share/logstash/pipeline/logstash.conf"
      # - "./logstash/pipeline/debug-logstash.conf:/usr/share/logstash/pipeline/debug-logstash.conf"
      - "./logstash/pipeline:/usr/share/logstash/pipeline"
      - "./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml"
      - "./logstash/config/debug-logstash.yml:/usr/share/logstash/config/debug-logstash.yml"
      - "./logstash/logs:/usr/share/logstash/logs"
    environment:
      - xpack.monitoring.enabled=false
      - ELASTIC_USER=elastic
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
      - ELASTIC_HOSTS=https://es01:9200
    # mine
      - SPARK_LS_PORT=${SPARK_LS_PORT}
      - SPARK_LS_HOST=${SPARK_LS_HOST}
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -s -I http://localhost:9600",
        ]
      interval: 10s
      timeout: 10s
      retries: 120
      
  spark-filebeat01:
    depends_on:
      spark-logstash01:
        condition: service_healthy
    image: docker.elastic.co/beats/filebeat:${STACK_VERSION}
    container_name: spark-filebeat01
    # user: root
    volumes:
      - "./filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro"
      # For testing purposes
      - "./spark-events:/usr/share/filebeat/spark-events:ro" 
      # - "/home/gxbrooks/GitHub/pyspark-playground/spark-events:/usr/share/filebeat/json:ro"
    # environment:
      # - ELASTIC_USER=elastic
      # - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
      # - ELASTIC_HOSTS=https://es01:9200
      # - KIBANA_HOSTS=http://kibana:5601
      # - LOGSTASH_HOSTS=http://logstash01:9600
    # command:
      # - --strict.perms=false
    environment:
    # mine
      - SPARK_LS_PORT=${SPARK_LS_PORT}
      - SPARK_LS_HOST=${SPARK_LS_HOST}
    

