
#
# System dependencies
# 
# kibana -------------------------------------------------->
#   \
#    \----------------> init-kibana --|
#                  /                  v
#                 / 
# es01 --> init-kibana-password --|
#    \                            v
#     \ 
#      \--> init-index ---> logstash01 ---------------> 
#                       |          \
#                       v           \ --> spark-* ->
#

volumes:
  certs:
    driver: local
  esdata:
    driver: local
  kibanadata:
    driver: local
  logstash01:
    driver: local
  spark-logs:


networks:
  default:
    name: elastic
    external: false

services:

  es01:
    build:
      context: .
      dockerfile: Dockerfile
    image: cert-es-base
    labels:
      co.elastic.logs/module: elasticsearch
    volumes:
      - esdata:/usr/share/elasticsearch/data
      - certs:/usr/share/elasticsearch/config/certs
      # only needed for debugging initializations
      - ./init:/usr/share/elasticsearch/init
      #   docker exec -it <Container-ID> bash
      # or through the Docker Desktop console
    ports:
      - ${ES_PORT}:9200
    environment:
      - node.name=es01
      - cluster.name=${CLUSTER_NAME}
      - discovery.type=single-node
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
      - bootstrap.memory_lock=true
      # Xpack must be rooted at /usr/share/elasticsearch/config, so start with certs/
      - xpack.security.enabled=true
      - xpack.security.http.ssl.enabled=true
      - xpack.security.http.ssl.key=certs/es01/es01.key
      - xpack.security.http.ssl.certificate=certs/es01/es01.crt
      - xpack.security.http.ssl.certificate_authorities=certs/ca/ca.crt
      - xpack.security.transport.ssl.enabled=true
      - xpack.security.transport.ssl.key=certs/es01/es01.key
      - xpack.security.transport.ssl.certificate=certs/es01/es01.crt
      - xpack.security.transport.ssl.certificate_authorities=certs/ca/ca.crt
      - xpack.security.transport.ssl.verification_mode=certificate
      - xpack.license.self_generated.type=${LICENSE}
      # For using Watcher as an HTTPS client
      - xpack.http.ssl.certificate_authorities=["/usr/share/elasticsearch/config/certs/ca/ca.crt"]
      # https://handlers.sans.edu/gbruneau/elk/TLS_elasticsearch_configuration.pdf
    mem_limit: ${ES_MEM_LIMIT}
    ulimits:
      memlock:
        soft: -1
        hard: -1
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -s --cacert config/certs/ca/ca.crt https://localhost:9200 | grep -q 'missing authentication credentials'",
        ]
      interval: 10s
      timeout: 10s
      retries: 120

  init-kibana-password:   
    image: cert-es-base
    volumes:
      - ./init:/usr/share/elasticsearch/init
      - certs:/usr/share/elasticsearch/config/certs
    command: bash -f ./init/bin/init-kibana-password.sh 
    environment:
      # do we need any of this? Taken from logstash
      # - xpack.monitoring.enabled=false
      - ELASTIC_USER=elastic
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
      - ELASTIC_HOSTS=https://es01:9200
      - KIBANA_PASSWORD=${KIBANA_PASSWORD}
    depends_on:
      es01:
        condition: service_healthy 

  kibana:
    image: docker.elastic.co/kibana/kibana:${STACK_VERSION} 
    container_name: kibana
    volumes:
      - certs:/usr/share/kibana/config/certs
      - ./init:/usr/share/kibana/init
      - kibanadata:/usr/share/kibana/data
    labels:
      co.elastic.logs/module: kibana
    ports:
      - ${KIBANA_PORT}:5601
    environment:
      - SERVERNAME=kibana
      - ELASTICSEARCH_HOSTS=https://es01:9200
      - ELASTICSEARCH_USERNAME=kibana_system
      - ELASTICSEARCH_PASSWORD=${KIBANA_PASSWORD}
      - ELASTICSEARCH_SSL_CERTIFICATEAUTHORITIES=config/certs/ca/ca.crt
      - XPACK_SECURITY_ENCRYPTIONKEY=${ENCRYPTION_KEY}
      - XPACK_ENCRYPTEDSAVEDOBJECTS_ENCRYPTIONKEY=${ENCRYPTION_KEY}
      - XPACK_REPORTING_ENCRYPTIONKEY=${ENCRYPTION_KEY}
    mem_limit: ${KB_MEM_LIMIT}
    depends_on:
      init-kibana-password:
        condition: service_completed_successfully
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -s -I http://localhost:5601 | grep -q 'HTTP/1.1 302 Found'",
        ]
      interval: 10s
      timeout: 10s
      retries: 120    
   
  init-kibana:
    image: cert-es-base
    volumes:
      - ./init:/usr/share/elasticsearch/init
      - certs:/usr/share/elasticsearch/config/certs
    command: bash -f ./init/bin/init-kibana.sh
    env_file:
      - .env
    # environment:
      # do we need any of this? Taken from logstash
      # - xpack.monitoring.enabled=false
      # - KIBANA_PORT=${KIBANA_PORT}
      # - KIBANA_PASSWORD=${KIBANA_PASSWORD}
    depends_on:
      kibana:
        condition: service_healthy
      init-kibana-password:
        condition: service_completed_successfully

  init-index:
    image: cert-es-base
    volumes:
      - ./init:/usr/share/elasticsearch/init
      - certs:/usr/share/elasticsearch/config/certs
    command: bash -f ./init/bin/init-index.sh 
    environment:
      # do we need any of this? Taken from logstash
      # - xpack.monitoring.enabled=false
      - ELASTIC_USER=elastic
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
      - ELASTIC_HOSTS=https://es01:9200
      # dubious we need kibana here
      - KIBANA_PASSWORD=${KIBANA_PASSWORD}
    depends_on:
      es01:
        condition: service_healthy

# mine

  logstash01:
    image: docker.elastic.co/logstash/logstash:8.14.3 #${STACK_VERSION} 
    container_name: logstash01
    labels:
      co.elastic.logs/module: logstash
    user: root
    ports: 
        - "${LS_SPARK_EVENTS_PORT}:${LS_SPARK_EVENTS_PORT}"
        - "${LS_DOCKER_METRICS_PORT}:${LS_DOCKER_METRICS_PORT}"
        - "9600:9600"
    volumes:
      - certs:/usr/share/logstash/certs
      - "./logstash/pipeline:/usr/share/logstash/pipeline"
      - "./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml"
      - "./logstash/config/debug-logstash.yml:/usr/share/logstash/config/debug-logstash.yml"
      - "./logstash/logs:/usr/share/logstash/logs"
    environment:
      - xpack.monitoring.enabled=false
      - ELASTIC_USER=elastic
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
      - ELASTIC_HOSTS=https://es01:9200
      - LS_HOST=${LS_HOST}
      - LS_SPARK_EVENTS_PORT=${LS_SPARK_EVENTS_PORT}
      - LS_DOCKER_METRICS_PORT=${LS_DOCKER_METRICS_PORT}
    depends_on:
      es01:
        condition: service_healthy
      init-index:
        condition: service_completed_successfully
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -s -I http://localhost:9600",
        ]
      interval: 10s
      timeout: 10s
      retries: 120
 
  spark-master:
    container_name: da-spark-master
    build: ./spark
    image: da-spark-image
    entrypoint: ['./entrypoint.sh', 'master']
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080" ]
      interval: 5s
      timeout: 3s
      retries: 3
    volumes:
      - ./spark/data:/opt/spark/data
      - ./spark/apps:/opt/spark/apps
      - ./spark-events:/opt/spark/spark-events
      - ./elastic-agent/elastic-agent-master.yml:/opt/Elastic/Agent/elastic-agent.yml
      - certs:/opt/Elastic/certs
    env_file:
      - spark/.env.spark
      - .env
    depends_on:
      logstash01:
        condition: service_healthy
    ports:
      - '9090:8080'
      - '7077:7077'

  spark-history-server:
    container_name: da-spark-history
    image: da-spark-image
    entrypoint: ['./entrypoint.sh', 'history']
    depends_on:
      spark-master:
        condition: service_healthy
      logstash01:
        condition: service_healthy
    env_file:
      - spark/.env.spark
      - .env
    volumes:
      - ./spark-events:/opt/spark/spark-events
      - ./elastic-agent/elastic-agent-history.yml:/opt/Elastic/Agent/elastic-agent.yml
      - certs:/opt/Elastic/certs
    ports:
      - '18080:18080'

  spark-worker:
#    container_name: da-spark-worker
    image: da-spark-image
    entrypoint: ['./entrypoint.sh', 'worker']
    depends_on:
      spark-master:
        condition: service_healthy
      logstash01:
        condition: service_healthy
    env_file:
      - spark/.env.spark
      - .env
    volumes:
      - ./spark/data:/opt/spark/data
      - ./spark/apps:/opt/spark/apps
      # - spark-logs:/opt/spark/spark-events
      - ./spark-events:/opt/spark/spark-events
      - ./elastic-agent/elastic-agent-worker.yml:/opt/Elastic/Agent/elastic-agent.yml
      - certs:/opt/Elastic/certs
