---
# Main tasks file for spark role

# Always include centralized variables
- name: Include centralized Spark variables
  include_vars: "{{ playbook_dir | dirname | dirname }}/vars/spark_vars.yml"

# Ensure that the spark_version variable is available
- name: Display Spark version being used
  debug:
    msg: "Using Spark version: {{ spark_version }}"

- name: Template deployment manifests using centralized variables
  template:
    src: "{{ item }}"
    dest: "{{ k8s_config_dir }}/{{ item | basename | regex_replace('\\.yml\\.j2$', '.yaml') }}"
    mode: '0644'
  loop:
    - spark-master-deployment.yml.j2
    - spark-history-deployment.yml.j2
    - spark-worker-deployment.yml.j2

- name: Copy service manifests
  copy:
    src: "{{ project_root }}/spark/k8s/{{ item }}"
    dest: "{{ k8s_config_dir }}/{{ item }}"
    mode: '0644'
  loop:
    - spark-history-service.yaml
    - spark-master-service.yaml

- name: Apply service manifests
  k8s:
    kubeconfig: "{{ kubeconfig }}"
    state: present
    src: "{{ k8s_config_dir }}/{{ item }}"
  loop:
    - spark-master-service.yaml
    - spark-history-service.yaml
    
- name: Apply deployment manifests
  k8s:
    kubeconfig: "{{ kubeconfig }}"
    state: present
    src: "{{ k8s_config_dir }}/{{ item }}"
  loop:
    - spark-master-deployment.yaml
    - spark-history-deployment.yaml
    - spark-worker-deployment.yaml
