---
# Main tasks file for spark role

# Always include centralized variables
- name: Include centralized Spark variables
  include_vars: "{{ playbook_dir | dirname | dirname | dirname }}/vars/contexts/spark_ansible_vars.yml"

# Ensure that the spark_version variable is available
- name: Display Spark version being used
  debug:
    msg: "Using Spark version: {{ spark_version }}"

- name: Template deployment manifests using centralized variables
  template:
    src: "templates/{{ item }}"
    dest: "{{ k8s_config_dir }}/{{ item | regex_replace('\\.j2$', '') }}"
    mode: '0644'
  vars:
    SPARK_VERSION: "{{ spark_version }}"
  loop:
    - spark-master.yaml.j2
    - spark-history.yaml.j2
    - spark-worker.yaml.j2

- name: Copy service manifests
  copy:
    src: "files/k8s/{{ item }}"
    dest: "{{ k8s_config_dir }}/{{ item }}"
    mode: '0644'
  loop:
    - spark-history-service.yaml
    - spark-master-service.yaml
    - spark-master-headless.yaml

- name: Apply service manifests
  k8s:
    kubeconfig: "{{ kubeconfig }}"
    state: present
    src: "{{ k8s_config_dir }}/{{ item }}"
  loop:
    - spark-master-service.yaml
    - spark-master-headless.yaml
    - spark-history-service.yaml
    
- name: Apply deployment manifests
  k8s:
    kubeconfig: "{{ kubeconfig }}"
    state: present
    src: "{{ k8s_config_dir }}/{{ item }}"
  loop:
    - spark-master.yaml
    - spark-history.yaml
    - spark-worker.yaml
