apiVersion: k3d.io/v1alpha4
kind: Simple
metadata:
  name: spark-cluster
servers: 1
agents: 1
image: rancher/k3s:v1.29.4-k3s1
volumes:
  - /spark-data:/spark-data
  - /mnt/nfs/spark-events:/mnt/nfs/spark-events
ports:
  - port: 6443:6443 # Kubernetes API
  - port: 18080:18080 # Spark History UI
options:
  k3s:
    extraArgs:
      - "--tls-san=spark-master.local"
env:
  - name: TZ
    value: "America/Chicago"
