apiVersion: v1
kind: Service
metadata:
  name: jupyterhub
  namespace: spark
spec:
  selector:
    app: jupyterhub
  ports:
    - name: jupyter
      port: 8888
      targetPort: 8888
      protocol: TCP
      nodePort: 32080
  type: NodePort

