apiVersion: v1
kind: ConfigMap
metadata:
  name: local-registry-config
  namespace: spark
data:
  registries.yaml: |
    mirrors:
      "lab3.lan:5000":
        endpoint:
          - "http://lab3.lan:5000"
