# This file is automatically generated from variables.yaml by generate_env.py
# Do not edit manually!

export PYTHON_VERSION="3.11"
export JAVA_VERSION="17"
export PYSPARK_PYTHON="python3.11"
export SPARK_VERSION="4.0.1"
export SPARK_MASTER_EXTERNAL_HOST="Lab2.lan"
export SPARK_MASTER_EXTERNAL_PORT="31686"
export SPARK_EVENTS_DIR="/mnt/spark/events"
export SPARK_CONF_DIR="/home/gxbrooks/repos/elastic-on-spark/spark/conf"
export OTEL_EXPORTER_OTLP_ENDPOINT="http://Lab2.lan:31317"
export SPARK_DATA_MOUNT="/mnt/spark/data"
export HDFS_DEFAULT_FS="hdfs://hdfs-namenode:9000"
