# This file is automatically generated from vars/variables.yaml by generate_env.py
# Do not edit manually!

export PYTHON_VERSION="3.8"
export PYSPARK_PYTHON="python3.8"
export SPARK_MASTER_HOST="Lab2.local"
export SPARK_MASTER_PORT="31472"
export SPARK_EVENTS_DIR="/mnt/spark/events"
export SPARK_CONF_DIR="/home/gxbrooks/repos/spark-observability/spark/conf"
export SPARK_DATA_MOUNT="/mnt/spark/data"
export HDFS_DEFAULT_FS="hdfs://hdfs-namenode:9000"
