# Configuration file version
apiVersion: 1

datasources:
  - name: Elasticsearch
    type: elasticsearch
    access: proxy
    url: https://es01:9200/
    basicAuth: true
    basicAuthUser: elastic
    isDefault: false
    # make UID constant across each instance of a Grafana container
    # Needed for the dashboards that use the data source to load
    uid: spark-elasticsearch
    jsonData:
      esVersion: ${STACK_VERSION}
      timeField: "@timestamp"
      timeout: 300
      # need to implement TLS
      tlsSkipVerify: true
      maxConcurrentShardRequests: 5
    secureJsonData:
      # password needs to be parametized and secured
      basicAuthPassword: ${ELASTIC_PASSWORD}

  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: false
    uid: prometheus
    jsonData:
      timeInterval: 30s
      httpMethod: POST
    editable: true

  - name: Tempo
    type: tempo
    access: proxy
    url: http://tempo:3200
    isDefault: false
    uid: tempo
    jsonData:
      httpMethod: GET
      tracesToLogs:
        datasourceUid: spark-elasticsearch
        tags: ['job', 'instance', 'pod', 'namespace']
        mappedTags: [{ key: 'service.name', value: 'service' }]
        mapTagNamesEnabled: false
        spanStartTimeShift: '1h'
        spanEndTimeShift: '1h'
        filterByTraceID: false
        filterBySpanID: false
      tracesToMetrics:
        datasourceUid: prometheus
        tags: [{ key: 'service.name', value: 'service' }, { key: 'job' }]
        queries:
          - name: 'Sample query'
            query: 'sum(rate(tempo_spanmetrics_latency_bucket{$$__tags}[5m]))'
      serviceMap:
        datasourceUid: prometheus
      nodeGraph:
        enabled: true
      search:
        hide: false
      lokiSearch:
        datasourceUid: spark-elasticsearch
    editable: true
