# Configuration file version
apiVersion: 1

datasources:
  - name: Elasticsearch
    type: elasticsearch
    access: proxy
    url: https://es01:9200/
    basicAuth: true
    basicAuthUser: elastic
    isDefault: false
    # make UID constant across each instance of a Grafana container
    # Needed for the dashboards that use the data source to load
    uid: spark-elasticsearch
    jsonData:
      esVersion: ${STACK_VERSION}
      timeField: "@timestamp"
      timeout: 300
      # need to implement TLS
      tlsSkipVerify: true
      maxConcurrentShardRequests: 5
    secureJsonData:
      # password needs to be parametized and secured
      basicAuthPassword: ${ELASTIC_PASSWORD}
