---
# Start ServiceNow MID Server on Lab3.
- name: Start MID Server
  hosts: observability
  become: true
  gather_facts: false
  vars_files:
    - "{{ playbook_dir }}/../../../../vars/contexts/servicenow_ansible_vars.yml"
    - "{{ playbook_dir }}/common/vars.yml"
  tasks:
    - name: Start MID Server systemd unit
      ansible.builtin.systemd:
        name: "{{ sn_mid_service_name }}.service"
        state: started
        enabled: true
      failed_when: false
