all:
  hosts:
    Lab1:
      ansible_host: Lab1
      ansible_user: gxbrooks
      ansible_connection: ssh
      ansible_port: 22
      ansible_ssh_private_key_file: C:\Users\gxbrooks\.ssh\id_rsa
      ansible_python_interpreter: C:\Users\gxbrooks\AppData\Local\Programs\Python\Python39\python.exe #adjust as needed
    Lab2:
      ansible_host: Lab2
      ansible_user: gxbrooks
      ansible_connection: ssh
      ansible_port: 22
      ansible_python_interpreter: /usr/bin/python3
      ansible_ssh_private_key_file: ~/.ssh/id_rsa
    GaryPC:
      ansible_host: GaryPC
      ansible_user: gxbrooks
      ansible_connection: ssh
      ansible_port: 22
      ansible_ssh_private_key_file: C:\Users\gxbrooks\.ssh\id_rsa
      ansible_python_interpreter: C:\Users\gxbrooks\AppData\Local\Programs\Python\Python39\python.exe #adjust as needed
    GaryPC_WSL:
      ansible_host: GaryPC
      ansible_user: gxbrooks
      ansible_connection: ssh
      ansible_port: 2222
      ansible_python_interpreter: /usr/bin/python3
      ansible_ssh_private_key_file: ~/.ssh/id_rsa
    Lab1_WSL:
      ansible_host: Lab1
      ansible_user: gxbrooks
      ansible_connection: ssh
      ansible_port: 2222
      ansible_python_interpreter: /usr/bin/python3
      ansible_ssh_private_key_file: ~/.ssh/id_rsa

  children:
    linux:
      hosts:
        Lab2:
    windows:
      hosts:
        Lab1:
        GaryPC:
    wsl:
      hosts:
        GaryPC_WSL:
        Lab1_WSL: