spark.master                           spark://spark-master:7077
spark.eventLog.enabled                 true
spark.eventLog.dir                     /opt/spark/spark-events
spark.history.fs.logDirectory          /opt/spark/spark-events
spark.executor.memory                  2g
spark.driver.memory                    2g

spark.executor.extraJavaOptions        -XX:+PrintGCDetails -XX:+PrintGCTimeStamps -Xloggc:/opt/spark/logs/executor_gc.log
spark.driver.extraJavaOptions          -XX:+PrintGCDetails -XX:+PrintGCTimeStamps -Xloggc:/opt/spark/logs/driver_gc.log

