spark.master                           spark://spark-master:7077
spark.eventLog.enabled                 true
spark.eventLog.dir                     /opt/spark/spark-events
spark.history.fs.logDirectory          /opt/spark/spark-events
spark.executor.memory                  8g
spark.driver.memory                    40g              

spark.executor.extraJavaOptions        -Xlog:gc*:file=/opt/spark/logs/executor.gc.log:utctime,uptime,level,tags,hostname,pid,tid:filecount=5,filesize=100m 
spark.driver.extraJavaOptions          -Xlog:gc*:file=/opt/spark/logs/executor.gc.log:utctime,uptime,level,tags,hostname,pid,tid:filecount=5,filesize=100m 
