---
- name: Start NFS Server
  hosts: nfs_servers
  become: true
  tasks:
    - name: Start NFS server
      systemd:
        name: nfs-server
        state: started

    - name: Apply NFS exports
      command: exportfs -ra
