elastic_agent_download_url: "https://artifacts.elastic.co/downloads/beats/elastic-agent/elastic-agent-{{ elastic_agent_version }}-{{ elastic_agent_os }}-{{ elastic_agent_arch }}.{{ elastic_agent_extension }}"
elastic_agent_enrollment_url: "YOUR_ENROLLMENT_URL"
elastic_agent_enrollment_token: "YOUR_ENROLLMENT_TOKEN"
elastic_agent_version: "8.11.1" # Replace with your desired version
