---
# Deploy one business application from specification.
# Input: sn_csdm_ba_spec

- name: Ensure business application
  ansible.builtin.include_tasks: ensure_cmdb_record.yml
  vars:
    sn_csdm_table: cmdb_ci_business_app
    sn_csdm_lookup_name: "{{ sn_csdm_ba_spec.name }}"
    sn_csdm_body: "{{ sn_csdm_ba_spec | dict2items | rejectattr('key', 'in', ['name', 'parent_business_application']) | items2dict }}"
    sn_csdm_patch_body: "{{ sn_csdm_ba_spec | dict2items | rejectattr('key', 'in', ['name', 'parent_business_application']) | items2dict }}"

- name: Record business application sys_id in registry
  ansible.builtin.set_fact:
    sn_csdm_registry: >-
      {{ sn_csdm_registry | combine(
           {'business_applications': sn_csdm_registry.business_applications | default({}) | combine({sn_csdm_ba_spec.name: sn_csdm_record_sys_id})},
           recursive=True) }}
