#
# System dependencies
# 
# kibana -------------------------------------------------->
#   \
#    \----------------> init-kibana --|
#                  /                  v
#                 / 
# es01 --> init-kibana-password --|
#    \                            v
#     \ 
#      \--> init-index ---> logstash01 ---------------> 
#                       |          \
#                       v           \ --> spark-* ->
#

volumes:
  esdata:
    driver: local
  kibanadata:
    driver: local
  spark-logs:
    driver: local


networks:
  default:
    name: elastic
    external: true

services:

  init-certs:
    image: docker.elastic.co/elasticsearch/elasticsearch:${STACK_VERSION}
    container_name: init-certs
    labels:
      role: "Init Certs"
    volumes:
      - /etc/ssl/private/elastic:/etc/ssl/private/elastic
      - /etc/ssl/certs/elastic:/etc/ssl/certs/elastic
      - ./certs:/usr/share/elasticsearch/certs   # For configs & scripts
      - ./shared:/opt/shared
    user: "0"
    command: bash -f ./certs/init-certs.sh
    # env_file:
    #   - .env
    
  es01:
    container_name: es
    build: 
      context: ./elasticsearch
      dockerfile: Dockerfile
      args:
        STACK_VERSION: ${STACK_VERSION}
    image: elasticsearch-python
    labels:
      co.elastic.logs/module: elasticsearch
      role: Elasticsearch
    volumes:
      - esdata:/usr/share/elasticsearch/data
      - /etc/ssl/private/elastic/certs:/usr/share/elasticsearch/config/certs
      - ./elasticsearch:/usr/share/elasticsearch/elasticsearch
      - ./shared:/opt/shared
    ports:
      - "${ELASTIC_PORT}:${ELASTIC_PORT}"
    environment:
      ELASTIC_PORT: ${ELASTIC_PORT}
      ELASTIC_HOST: ${ELASTIC_HOST}
      ELASTIC_PASSWORD: ${ELASTIC_PASSWORD}
      ELASTIC_USER: ${ELASTIC_USER}
      KIBANA_PORT: ${KIBANA_PORT}
      KIBANA_PASSWORD : ${KIBANA_PASSWORD}
      # is this needed by Elasticsearch?
      CA_CERT: "/usr/share/elasticsearch/config/certs/ca/ca.crt"
      PY_SCRIPTS: "/opt/shared/bin"
      PYTHONPATH: "/opt/shared/bin/api"
      node.name: es01
      cluster.name: "${CLUSTER_NAME}"
      discovery.type: "single-node"
      bootstrap.memory_lock: true
      # Xpack is rooted at /usr/share/elasticsearch/config, so start all certificate 
      # paths with "certs/"!!!
      xpack.security.enabled: true
      xpack.security.http.ssl.enabled: true
      xpack.security.http.ssl.key: "certs/es01/es01.key"
      xpack.security.http.ssl.certificate: "certs/es01/es01.crt"
      xpack.security.http.ssl.certificate_authorities: "certs/ca/ca.crt"
      xpack.security.transport.ssl.enabled: true
      xpack.security.transport.ssl.key: "certs/es01/es01.key"
      xpack.security.transport.ssl.certificate: "certs/es01/es01.crt"
      xpack.security.transport.ssl.certificate_authorities: "certs/ca/ca.crt"
      xpack.security.transport.ssl.verification_mode: "certificate"
      xpack.license.self_generated.type: "${LICENSE}"
      # For using Watcher as an HTTPS client
      # https://handlers.sans.edu/gbruneau/elk/TLS_elasticsearch_configuration.pdf
      # xpack.http.ssl.certificate_authorities: "certs/ca/ca.crt"
      xpack.http.ssl.certificate_authorities: "/usr/share/elasticsearch/config/certs/ca/ca.crt"
    # ES_MEM_LIMIT=1GB is too tight. Let's see where it floats...    
    deploy:
      resources:
        limits:
          memory: 4g
    ulimits:
      memlock:
        soft: -1
        hard: -1
    # depends_on:
    #   init-certs:
    #     condition: service_completed_successfully 
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -s --cacert config/certs/ca/ca.crt https://localhost:9200 | grep -q 'missing authentication credentials'",
        ]
      interval: 10s
      timeout: 10s
      retries: 120
      

  init-kibana-password:   
    image: elasticsearch-python
    labels:
      role: "Init Kibana Password"
    volumes:
      - ./elasticsearch:/usr/share/elasticsearch/elasticsearch
      - /etc/ssl/certs/elastic:/etc/ssl/certs/elastic
      - ./shared:/opt/shared
    command: bash -f ./elasticsearch/bin/init-kibana-password.sh 
    environment:
      # do we need any of this? Taken from logstash
      # - xpack.monitoring.enabled=false
      ELASTIC_USER: elastic
      ELASTIC_PASSWORD: ${ELASTIC_PASSWORD}
      ELASTIC_HOST: ${ELASTIC_HOST}
      ELASTIC_PORT: ${ELASTIC_PORT}
      KIBANA_PASSWORD: ${KIBANA_PASSWORD}
      CA_CERT: "/etc/ssl/certs/elastic/ca.crt"
      PY_SCRIPTS: "/opt/shared/bin"
      PYTHONPATH: "/opt/shared/bin/api"

    depends_on:
      es01:
        condition: service_healthy 
      init-certs:
        condition: service_completed_successfully

  kibana:
    image: docker.elastic.co/kibana/kibana:${STACK_VERSION} 
    container_name: kibana
    volumes:
      - /etc/ssl/certs/elastic:/etc/ssl/certs/elastic
      - ./shared:/opt/shared
      - kibanadata:/usr/share/kibana/data
    labels:
      co.elastic.logs/module: kibana
      role: "Kibana"
    ports:
      - ${KIBANA_PORT}:5601
    environment:
      # ELASTICSEARCH_HOSTS: https://${ELASTIC_HOST}:${ELASTIC_PORT}
      ELASTICSEARCH_HOSTS: https://es01:9200
      ELASTICSEARCH_USERNAME: kibana_system
      ELASTICSEARCH_PASSWORD: ${KIBANA_PASSWORD}
      ELASTICSEARCH_SSL_CERTIFICATEAUTHORITIES: "/etc/ssl/certs/elastic/ca.crt"
      XPACK_SECURITY_ENCRYPTIONKEY: ${ENCRYPTION_KEY}
      XPACK_ENCRYPTEDSAVEDOBJECTS_ENCRYPTIONKEY: ${ENCRYPTION_KEY}
      XPACK_REPORTING_ENCRYPTIONKEY: ${ENCRYPTION_KEY}
    mem_limit: ${KB_MEM_LIMIT}
    depends_on:
      es01:
        condition: service_healthy 
      init-kibana-password:
        condition: service_completed_successfully
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -s -I http://localhost:${KIBANA_PORT} | grep -q 'HTTP/1.1 302 Found'",
        ]
      interval: 10s
      timeout: 10s
      retries: 120    

  grafana:
    image: grafana/grafana-enterprise
    labels:
      role: "Grafana"
    container_name: grafana
    restart: unless-stopped
    ports:
      - '3000:3000'
    volumes:
      - "./grafana/data:/var/lib/grafana/data"
      - "./grafana/provisioning:/etc/grafana/provisioning"
      - "./grafana/grafana.ini:/etc/grafana/grafana.ini"
      - ./shared:/opt/shared
    environment:
      GF_SECURITY_ADMIN_USER: "admin"
      GF_SECURITY_ADMIN_PASSWORD: "mysecretpassword"
      # GF_SERVER_HOST: localhost
      GF_SERVER_HTTP_PORT: "3000"
      ELASTIC_USER: "elastic"
      ELASTIC_PASSWORD: ${ELASTIC_PASSWORD}
    depends_on:
      es01:
        condition: service_healthy 
      # init-index:
      #   condition: service_completed_successfully
        
  init-kibana:
    image: elasticsearch-python
    volumes:
      - ./elasticsearch:/usr/share/elasticsearch/elasticsearch
      - /etc/ssl/certs/elastic:/etc/ssl/certs/elastic
      - ./shared:/opt/shared
    command: bash -f ./elasticsearch/bin/init-kibana.sh
    environment:
      # do we need any of this? Taken from logstash
      xpack.monitoring.enabled: false
      ELASTIC_PASSWORD: ${ELASTIC_PASSWORD}
      ELASTIC_PORT: ${ELASTIC_PORT}
      ELASTIC_USER: ${ELASTIC_USER}
      KIBANA_HOST: ${KIBANA_HOST}
      KIBANA_PASSWORD : ${KIBANA_PASSWORD}
      KIBANA_PORT: ${KIBANA_PORT}
      CA_CERT: "/etc/ssl/certs/elastic/ca.crt"
      PY_SCRIPTS: "/opt/shared/bin"
      PYTHONPATH: "/opt/shared/bin/api"
    depends_on:
      kibana:
        condition: service_healthy
      init-kibana-password:
        condition: service_completed_successfully
      init-certs:
        condition: service_completed_successfully

  init-index:
    image: elasticsearch-python
    command: bash -f ./elasticsearch/bin/init-index.sh
    labels:
      role: "Init Index"
    volumes:
      - ./elasticsearch:/usr/share/elasticsearch/elasticsearch
      - /etc/ssl/certs/elastic:/etc/ssl/certs/elastic
      - ./shared:/opt/shared
    environment:
      ELASTIC_HOST: ${ELASTIC_HOST}
      ELASTIC_PASSWORD: ${ELASTIC_PASSWORD}
      ELASTIC_PORT: ${ELASTIC_PORT}
      ELASTIC_USER: ${ELASTIC_USER}
      CA_CERT: "/etc/ssl/certs/elastic/ca.crt"
      PY_SCRIPTS: "/opt/shared/bin"
      PYTHONPATH: "/opt/shared/bin/api"
    depends_on:
      es01:
        condition: service_healthy
      init-certs:
        condition: service_completed_successfully

  logstash01:
    image: docker.elastic.co/logstash/logstash:8.14.3 #${STACK_VERSION} 
    container_name: logstash01
    labels:
      co.elastic.logs/module: logstash
      role: "Logstash"
    # TODO: Logstash should not run a root, but it needs to be able to write to the
    # /mnt/c/Volumes/logs/spark/events directory, which is owned by root.
    user: root
    ports: 
        - "${LS_SPARK_EVENTS_PORT}:${LS_SPARK_EVENTS_PORT}"
        # TODO: Evantually metrics should be sent to reginal Logstash servers
        # and then fed up into Elasticsearch
        # - "${LS_DOCKER_METRICS_PORT}:${LS_DOCKER_METRICS_PORT}"
        - "9600:9600"
    volumes:
      - /etc/ssl/certs/elastic:/etc/ssl/certs/elastic
      - ./shared:/opt/shared
      - "./logstash/pipeline:/usr/share/logstash/pipeline:ro"
      - "./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml"
      # not used
      - "./logstash/config/debug-logstash.yml:/usr/share/logstash/config/debug-logstash.yml"
    environment:
      xpack.monitoring.enabled: "false"
      ELASTIC_USER: "elastic"
      ELASTIC_PASSWORD: ${ELASTIC_PASSWORD}
      ELASTIC_HOSTS: "https://${ELASTIC-HOST}:${ELASTIC_PORT}"
      ELASTIC_URL: ${ELASTIC_URL}
      LS_HOST: ${LS_HOST}
      LS_SPARK_EVENTS_PORT: ${LS_SPARK_EVENTS_PORT}
      LS_DOCKER_METRICS_PORT: ${LS_DOCKER_METRICS_PORT}
      # TODO: environment variables to include time zone. 
      TZ: "America/Chicago"
    depends_on:
      es01:
        condition: service_healthy
      init-index:
        condition: service_completed_successfully
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -s -I http://localhost:9600",
        ]
      interval: 10s
      timeout: 10s
      retries: 120
 
  spark-master:
    container_name: da-spark-master
    build: 
      context: ./spark
      dockerfile: Dockerfile
      args:
        SPARK_VERSION: ${SPARK_VERSION}
        SPARK_MASTER: ${SPARK_MASTER}
        SPARK_HOME: ${SPARK_HOME}
        SPARK_MASTER_HOST: ${SPARK_MASTER_HOST}
        SPARK_MASTER_PORT: ${SPARK_MASTER_PORT}
        HADOOP_HOME: ${HADOOP_HOME}
        PYSPARK_PYTHON: ${PYSPARK_PYTHON}
        ELASTIC_AGENT_HOME: ${ELASTIC_AGENT_HOME}
        ELASTIC_AGENT_STACK_VERSION: ${ELASTIC_AGENT_STACK_VERSION}
        GOOGLE_APPLICATION_CREDENTIALS: ${GOOGLE_APPLICATION_CREDENTIALS}
      
    image: da-spark-image
    entrypoint: ["./entrypoint.sh", 'master']
    labels:
      role: "Spark Master"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080" ]
      interval: 5s
      timeout: 3s
      retries: 3
      start_period: 60s 
    hostname: spark-master
    env_file:
      - .env
    # TODO: allow for multiple Spark Masters
    # environment:
    #   - SPARK_LOG_DIR=/opt/spark/logs/${COMPOSE_PROJECT_NAME}_${SERVICE_NAME}_${INDEX}
    #   - SPARK_ROLE_NAME=${COMPOSE_PROJECT_NAME}_${SERVICE_NAME}_${INDEX}
    volumes:
      - /mnt/c/Volumes/logs/spark/events:/opt/spark/spark-events
      - /mnt/c/Volumes/logs/spark/spark-master:/opt/spark/logs
      - ./spark/code:/opt/spark/code
      - ../spark/data:/opt/spark/data
      - ./spark/apps:/opt/spark/apps
      - ./spark/conf/log4j2.properties:/opt/spark/conf/log4j2.properties
      - ./spark/conf/spark-defaults.conf:/opt/spark/conf/spark-defaults.conf
      - ./spark/conf/spark-env.sh:/opt/spark/conf/spark-env.sh
      # elastic-agent moved outside docker
      #- ./elastic-agent/elastic-agent.yml:/etc/elastic-agent/elastic-agent.yml
      # entrypoint copied in in the Dockerfile
      # - ./spark/entrypoint.sh:${SPARK_HOME}/entrypoint.sh
      - ./shared:/opt/shared
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "/var/lib/docker/containers:/var/lib/docker/containers:ro"
    # depends_on:
    #   # for sending metrics to Elastic
    #   es01:
    #     condition: service_healthy
    ports:
      - '9090:8080'
      - '7077:7077'

  spark-history:
    container_name: da-spark-history
    image: da-spark-image
    entrypoint: ["./entrypoint.sh", 'history']
    labels:
      role: "Spark Historian"
    depends_on:
      spark-master:
        condition: service_healthy
      # # for sending metrics to Elastic
      # es01:
      #   condition: service_healthy
      # # Make sure Logstash is running and all indicies are defined before starting Elastic Agent
      # logstash01:
      #   condition: service_healthy
      # init-index:
      #   condition: service_completed_successfully
    hostname: spark-history
    # environment:
    #   - SPARK_LOG_DIR=/opt/spark/logs/${COMPOSE_PROJECT_NAME}_${SERVICE_NAME}_${INDEX}
    #   - SPARK_ROLE_NAME=${COMPOSE_PROJECT_NAME}_${SERVICE_NAME}_${INDEX}
    env_file:
      # - .spark.env
      - .env
    volumes:
      - /mnt/c/Volumes/logs/spark/events:/opt/spark/spark-events
      - /mnt/c/Volumes/logs/spark/spark-history:/opt/spark/logs
      - ../spark-data:/opt/spark/data
      - ./spark/apps:/opt/spark/apps
      - ./spark/conf/log4j2.properties:/opt/spark/conf/log4j2.properties
      - ./spark/conf/spark-defaults.conf:/opt/spark/conf/spark-defaults.conf
      - ./spark/conf/spark-env.sh:/opt/spark/conf/spark-env.sh
      # elastic-agent moved outside docker
      # - ./elastic-agent/elastic-agent.yml:/etc/elastic-agent/elastic-agent.yml
      # entrypoint copied in in the Dockerfile
      # - ./spark/entrypoint.sh:${SPARK_HOME}/entrypoint.sh
      # - ./certs:/opt/Elastic/certs
      - ./shared:/opt/shared
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "/var/lib/docker/containers:/var/lib/docker/containers:ro"
    ports:
      - '18080:18080'

  spark-worker:
#    container_name: da-spark-worker
    image: da-spark-image
    entrypoint: ["./entrypoint.sh", 'worker']
    labels:
      role: "Spark Worker"
    depends_on:
      spark-master:
        condition: service_healthy
      # # for sending metrics to Elastic
      # es01:
      #   condition: service_healthy
    hostname: spark-worker
    # environment:
    #   - SPARK_LOG_DIR=/opt/spark/logs/${COMPOSE_PROJECT_NAME}_${SERVICE_NAME}_${INDEX}
    #   - SPARK_ROLE_NAME=${COMPOSE_PROJECT_NAME}_${SERVICE_NAME}_${INDEX}
    env_file:
      #- .spark.env
      - .env
    volumes:
      - /mnt/c/Volumes/logs/spark/events:/opt/spark/spark-events
      - /mnt/c/Volumes/logs/spark/spark-worker:/opt/spark/logs
      - ../spark/data:/opt/spark/data
      - ./spark/apps:/opt/spark/apps
      - ./spark/conf/log4j2.properties:/opt/spark/conf/log4j2.properties
      - ./spark/conf/spark-defaults.conf:/opt/spark/conf/spark-defaults.conf
      - ./spark/conf/spark-env.sh:/opt/spark/conf/spark-env.sh
      - ./shared:/opt/shared
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "/var/lib/docker/containers:/var/lib/docker/containers:ro"
    ports:
      - '8081:8081'

  spark-client:
    image: da-spark-image
    container_name: spark-client
    depends_on:
      - spark-master
    volumes:
      - /mnt/c/Volumes/logs/spark/events:/opt/spark/spark-events
      - /mnt/c/Volumes/logs/spark/spark-client:/opt/spark/logs
      - ./spark/code:/opt/spark/code
      - ../spark/data:/opt/spark/data
      - ./spark/apps:/opt/spark/apps
      - ./spark/conf/log4j2.properties:/opt/spark/conf/log4j2.properties
      - ./spark/conf/spark-defaults.conf:/opt/spark/conf/spark-defaults.conf
      - ./spark/conf/spark-env.sh:/opt/spark/conf/spark-env.sh
      - ./shared:/opt/shared
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "/var/lib/docker/containers:/var/lib/docker/containers:ro"
      
    env_file:
      #- .spark.env
      - .env
    ports:
      # Expose the Spark Application UI (4040+) from this client container
      - "4040-4050:4040-4050"
    environment:
      SPARK_MODE: client
      SPARK_MASTER_URL: spark://spark-master:7077
      # Crucial for UI to be accessible from host and for executors to connect back
      SPARK_DRIVER_HOST: spark-client # The internal Docker network hostname of this container
      # SPARK_DRIVER_BINDADDRESS: 0.0.0.0 # Bind to all interfaces within the container
      # SPARK_LOCAL_IP: 0.0.0.0 # Binds to all interfaces within the container
      # Configure PySpark to use IPython as the driver's Python interpreter
      PYSPARK_DRIVER_PYTHON: ipython
      PYSPARK_DRIVER_PYTHON_OPTS: "" # Add any specific IPython options if needed (e.g., --no-color)
      PYSPARK_PYTHON: python3 # Ensure workers use standard python (adjust if you need specific python versions)
    command: ["tail", "-f", "/dev/null"] # Keep the client container running