#!/usr/bin/env python3
"""
Data-Driven Variable Configuration Generator

Generates context-specific configuration files from centralized variable definitions.

Architecture:
  vars/variables.yaml  - Single source of truth for all variables
  vars/contexts.yaml   - Specification of output contexts and file formats
  generate_env.py - This script: transforms variables into context-specific files

Usage:
  ./generate_env.py                    # Generate all contexts
  ./generate_env.py spark-client       # Generate specific context
  ./generate_env.py -f                 # Force regeneration of all
  ./generate_env.py -v spark-image     # Verbose output for specific context
"""
import yaml
import os
import datetime
import sys
import argparse
from pathlib import Path

# Directory layout
SCRIPT_DIR = Path(__file__).resolve().parent
REPO_ROOT = SCRIPT_DIR.parent

# Configuration files
VARIABLES_FILE = SCRIPT_DIR / 'variables.yaml'
CONTEXTS_FILE = SCRIPT_DIR / 'contexts.yaml'

# Type to writer function mapping
WRITER_FUNCTIONS = {
    'env': 'write_env',
    'shell_env': 'write_shell_env',
    'toml': 'write_toml',
    'configmap': 'write_configmap',
    'ansible_vars': 'write_ansible_vars',
}


def load_variables():
    """Load variable definitions from vars/variables.yaml"""
    try:
        with VARIABLES_FILE.open() as f:
            return yaml.safe_load(f)
    except (yaml.YAMLError, IOError) as e:
        print(f"Error loading variables from {VARIABLES_FILE}: {e}")
        sys.exit(1)


def load_contexts():
    """Load context specifications from vars/contexts.yaml"""
    try:
        with CONTEXTS_FILE.open() as f:
            spec = yaml.safe_load(f)
            return spec.get('contexts', [])
    except (yaml.YAMLError, IOError) as e:
        print(f"Error loading contexts from {CONTEXTS_FILE}: {e}")
        sys.exit(1)


def get_vars(variables, context_name):
    """Extract variables applicable to a specific context
    
    Supports two formats:
    1. Simple format: {'value': '...', 'contexts': [...]}
    2. Context-specific format: {'values': {'default': '...', 'context1': '...'}, 'contexts': [...]}
    """
    result = {}
    for k, v in variables.items():
        if context_name not in v.get('contexts', []):
            continue
        
        # Check for context-specific values
        if 'values' in v:
            # Use context-specific value if available, otherwise try default, otherwise empty
            values_dict = v['values']
            if context_name in values_dict:
                value = values_dict[context_name]
            elif 'default' in values_dict:
                value = values_dict['default']
            else:
                # No match and no default - use first available value as fallback
                value = list(values_dict.values())[0] if values_dict else ''
        else:
            # Fall back to simple 'value' format
            value = v.get('value', '')
        
        result[k] = value
    return result


def write_env(vars_dict, filename):
    """Write environment variables to a file in KEY=VALUE format (no export)"""
    try:
        with open(filename, 'w') as f:
            f.write('# This file is automatically generated from vars/variables.yaml by vars/generate_env.py\n')
            f.write('# Do not edit manually!\n\n')
            for k, v in vars_dict.items():
                f.write(f'{k}={v}\n')
        return True
    except IOError as e:
        print(f"Error writing to {filename}: {e}")
        return False


def write_shell_env(vars_dict, filename):
    """Write variables to shell environment file with export statements"""
    try:
        with open(filename, 'w') as f:
            f.write('# This file is automatically generated from vars/variables.yaml by vars/generate_env.py\n')
            f.write('# Do not edit manually!\n\n')
            
            for k, v in vars_dict.items():
                f.write(f'export {k}="{v}"\n')
        return True
    except IOError as e:
        print(f"Error writing to {filename}: {e}")
        return False


def write_toml(vars_dict, filename):
    """Write environment variables to a TOML file"""
    try:
        with open(filename, 'w') as f:
            f.write('# This file is automatically generated from vars/variables.yaml by vars/generate_env.py\n')
            f.write('# Do not edit manually!\n\n')
            f.write('[env]\n')
            for k, v in vars_dict.items():
                if isinstance(v, str):
                    f.write(f'{k} = "{v}"\n')
                else:
                    f.write(f'{k} = {v}\n')
        return True
    except IOError as e:
        print(f"Error writing to {filename}: {e}")
        return False


def write_configmap(vars_dict, filename):
    """Write environment variables to a Kubernetes ConfigMap YAML file"""
    try:
        with open(filename, 'w') as f:
            f.write('# This file is automatically generated from vars/variables.yaml by vars/generate_env.py\n')
            f.write('# Do not edit manually!\n\n')
            f.write('apiVersion: v1\n')
            f.write('kind: ConfigMap\n')
            f.write('metadata:\n')
            f.write('  name: spark-configmap\n')
            f.write('  namespace: spark\n')
            f.write('data:\n')
            for k, v in vars_dict.items():
                f.write(f'  {k}: "{v}"\n')
        return True
    except IOError as e:
        print(f"Error writing to {filename}: {e}")
        return False


def write_ansible_vars(vars_dict, filename):
    """Write variables to Ansible variables YAML file with structured formatting"""
    try:
        with open(filename, 'w') as f:
            f.write('# Centralized variables for Ansible playbooks and roles\n')
            f.write('# This file is automatically generated from vars/variables.yaml by vars/generate_env.py\n')
            f.write('# Do not edit manually!\n\n')
            
            # Write Spark version first if it exists
            if 'SPARK_VERSION' in vars_dict:
                f.write(f'# Spark version\nspark_version: "{vars_dict["SPARK_VERSION"]}"\n\n')
              
            # Write registry configuration
            f.write('# Registry and image configuration (using local registry on Lab2)\n')
            f.write('registry_host: "lab2.local:5000"\n')
            f.write('spark_image: "{{ registry_host }}/spark"\n')
            f.write('spark_tag: "{{ spark_version }}"\n\n')
              
            # Write paths and directories
            f.write('# Paths and directories\n')
            if 'SPARK_EVENTS_DIR' in vars_dict:
                f.write(f'spark_events_dir: "{vars_dict["SPARK_EVENTS_DIR"]}"\n')
            if 'SPARK_HOME' in vars_dict:
                f.write(f'spark_home: "{vars_dict["SPARK_HOME"]}"\n')
            f.write('\n')
            
            # Write Elastic related settings
            elastic_vars = {k: v for k, v in vars_dict.items() if k.startswith('ELASTIC_')}
            if elastic_vars:
                f.write('# Elasticsearch settings\n')
                for key, value in elastic_vars.items():
                    var_name = key.lower()
                    f.write(f'{var_name}: "{value}"\n')
                f.write('\n')
            
            # Write Kubernetes settings
            f.write('# Kubernetes-specific settings\n')
            f.write('k8s_namespace: "spark"\n')
        return True
    except IOError as e:
        print(f"Error writing to {filename}: {e}")
        return False


def needs_update(source_files, target_file):
    """
    Check if target file needs to be updated by comparing modification times
    
    Args:
        source_files: List of source files to check (vars/variables.yaml, vars/contexts.yaml)
        target_file: The generated file to check
    
    Returns:
        String describing why update is needed, or False if up to date
    """
    # If target doesn't exist, it needs to be created
    if not target_file.exists():
        return "Target file does not exist"
    
    # Check if any source file is newer than target
    try:
        target_mtime = target_file.stat().st_mtime
        
        for source_file in source_files:
            if not source_file.exists():
                continue
                
            source_mtime = source_file.stat().st_mtime
            
            if source_mtime > target_mtime:
                source_time = datetime.datetime.fromtimestamp(source_mtime).isoformat()
                target_time = datetime.datetime.fromtimestamp(target_mtime).isoformat()
                return f"Source file {source_file} ({source_time}) is newer than target ({target_time})"
    except OSError as e:
        return f"Error checking file timestamps: {e}"
    
    return False


def main(requested_contexts=None, force=False, verbose=False):
    """
    Main entry point for variable generation
    
    Args:
        requested_contexts: List of context names to generate (None = all)
        force: Force regeneration even if files are up to date
        verbose: Show verbose output
    
    Returns:
        0 on success, 1 on error
    """
    # Load configuration
    variables = load_variables()
    contexts = load_contexts()
    
    if not contexts:
        print(f"No contexts defined in {CONTEXTS_FILE}")
        return 1
    
    # Build context lookup by name
    context_map = {ctx['name']: ctx for ctx in contexts}
    
    # Determine which contexts to generate
    if requested_contexts:
        # Validate requested contexts
        invalid_contexts = [c for c in requested_contexts if c not in context_map]
        if invalid_contexts:
            print(f"Error: Unknown context(s): {', '.join(invalid_contexts)}")
            print(f"Available contexts: {', '.join(context_map.keys())}")
            return 1
        contexts_to_generate = [context_map[c] for c in requested_contexts]
    else:
        # Generate all contexts
        contexts_to_generate = contexts
    
    # Source files for timestamp checking
    source_files = [VARIABLES_FILE, CONTEXTS_FILE]
    
    # Track results
    changes_made = False
    errors = []
    
    # Generate each context
    for context in contexts_to_generate:
        context_name = context['name']
        output_type = context['type']
        output_file = context['output']
        output_path = (REPO_ROOT / output_file).resolve()
        description = context.get('description', 'No description')
        
        # Validate output type
        if output_type not in WRITER_FUNCTIONS:
            print(f"Error: Unknown output type '{output_type}' for context '{context_name}'")
            print(f"Supported types: {', '.join(WRITER_FUNCTIONS.keys())}")
            errors.append(context_name)
            continue
        
        # Check if update is needed
        update_reason = needs_update(source_files, output_path) if not force else "Force flag set"
        
        if not force and not update_reason:
            if verbose:
                print(f"✓ Skipping {output_file} (up to date)")
            continue
        
        # Display what we're doing
        if force:
            print(f"→ Generating {output_path} for context '{context_name}' (forced)")
        else:
            print(f"→ Generating {output_path} for context '{context_name}'")
            if verbose:
                print(f"  Reason: {update_reason}")
                print(f"  Type: {output_type}")
                print(f"  Description: {description}")
        
        # Ensure output directory exists
        output_dir = output_path.parent
        output_dir.mkdir(parents=True, exist_ok=True)
        
        # Extract variables for this context
        vars_dict = get_vars(variables, context_name)
        
        if verbose:
            print(f"  Variables: {len(vars_dict)} extracted")
        
        # Get the writer function
        writer_func_name = WRITER_FUNCTIONS[output_type]
        writer_func = globals()[writer_func_name]
        
        # Generate the file
        success = writer_func(vars_dict, str(output_path))
        
        if success:
            changes_made = True
            print(f"✓ Successfully generated {output_file}")
        else:
            print(f"✗ Failed to generate {output_file}")
            errors.append(context_name)
    
    # Summary
    if errors:
        print(f"\n✗ Completed with {len(errors)} error(s): {', '.join(errors)}")
        return 1
    elif changes_made:
        print(f"\n✓ All requested files generated successfully")
        return 0
    else:
        print(f"\n✓ All files up to date")
        return 0


if __name__ == '__main__':
    parser = argparse.ArgumentParser(
        description='Generate context-specific configuration files from centralized variables',
        epilog='Examples:\n'
               '  %(prog)s                    # Generate all contexts\n'
               '  %(prog)s spark-client       # Generate specific context\n'
               '  %(prog)s -f                 # Force regeneration\n'
               '  %(prog)s -v spark-image     # Verbose output\n',
        formatter_class=argparse.RawDescriptionHelpFormatter
    )
    
    parser.add_argument(
        'contexts',
        nargs='*',
        help='Contexts to generate (if none specified, all will be generated)'
    )
    parser.add_argument(
        '-f', '--force',
        action='store_true',
        help='Force regeneration even if files are up to date'
    )
    parser.add_argument(
        '-v', '--verbose',
        action='store_true',
        help='Show verbose output'
    )
    
    args = parser.parse_args()
    
    contexts = args.contexts if args.contexts else None
    result = main(contexts, args.force, args.verbose)
    sys.exit(result)
