Environment=ELASTIC_HOST_EXTERNAL="GaryPC.local"
Environment=ELASTIC_USER="elastic"
Environment=ELASTIC_PASSWORD="myElastic2025"
Environment=ELASTIC_URL_EXTERNAL="https://GaryPC.local:9200"
Environment=KUBERNETES_API_SERVER="Lab2.local"
Environment=CA_CERT_LINUX_PATH="/etc/ssl/certs/elastic/ca.crt"
Environment=LS_HOST_EXTERNAL="GaryPC.local"
Environment=LS_SPARK_EVENTS_PORT="5050"
Environment=SPARK_EVENTS_DIR="/mnt/spark/events"
