# This file is automatically generated from variables.yaml by generate_env.py
# Do not edit manually!

export ELASTIC_HOST_EXTERNAL="GaryPC.lan"
export ELASTIC_USER="elastic"
export ELASTIC_PASSWORD="myElastic2025"
export ELASTIC_URL_EXTERNAL="https://GaryPC.lan:9200"
export CA_CERT_LINUX_PATH="/etc/ssl/certs/elastic/ca.crt"
export LS_HOST_EXTERNAL="GaryPC.lan"
export LS_SPARK_EVENTS_PORT="5050"
export SPARK_EVENTS_DIR="/mnt/spark/events"
