# You can add more variables here if needed

elastic_agent_version: "8.11.1" # Replace with your desired version
elastic_agent_download_url: "https://artifacts.elastic.co/downloads/beats/elastic-agent/elastic-agent-{{ elastic_agent_version }}-{{ elastic_agent_os }}-{{ elastic_agent_arch }}.{{ elastic_agent_extension }}"
elastic_agent_enrollment_url: "http://your-enrollment-url" # Replace with your actual enrollment URL
elastic_agent_enrollment_token: "your-enrollment-token" # Replace with your actual enrollment token

