---
- name: Scale Spark workers in Kubernetes
  hosts: spark_kubernetes:&linux
  become: true
  vars_files:
    - ../../variables.yaml
  tasks:
    - name: Scale Spark workers
      k8s:
        kubeconfig: /home/{{ ansible_user }}/.kube/config
        kind: Deployment
        name: spark-worker
        namespace: default
        replicas: "{{ spark_runtime.worker_replicas | default(3) }}"
        state: present
      when: inventory_hostname == groups['spark_kubernetes'][0]
