---
- name: Stop Kubernetes workloads
  hosts: spark_kubernetes:&linux
  become: true
  vars_files:
    - ../../variables.yaml
  tasks:
    - name: Remove Spark master
      k8s:
        kubeconfig: /home/{{ ansible_user }}/.kube/config
        state: absent
        src: ../../spark/k8s/spark-master-deployment.yaml
      when: inventory_hostname == groups['spark_kubernetes'][0]

    - name: Remove Spark history server
      k8s:
        kubeconfig: /home/{{ ansible_user }}/.kube/config
        state: absent
        src: ../../spark/k8s/spark-history-deployment.yaml
      when: inventory_hostname == groups['spark_kubernetes'][0]

    - name: Remove Spark workers
      k8s:
        kubeconfig: /home/{{ ansible_user }}/.kube/config
        state: absent
        src: ../../spark/k8s/spark-worker-deployment.yaml
      when: inventory_hostname == groups['spark_kubernetes'][0]
