---
- name: Upgrade Kubernetes components
  hosts: spark_kubernetes:&linux
  become: true
  vars_files:
    - ../../variables.yaml
  tasks:
    - name: Upgrade kubeadm
      apt:
        name: kubeadm
        state: latest

    - name: Upgrade kubelet and kubectl
      apt:
        name:
          - kubelet
          - kubectl
        state: latest

    - name: Drain node before upgrade
      command: kubectl drain {{ inventory_hostname }} --ignore-daemonsets --delete-local-data
      when: inventory_hostname == groups['spark_kubernetes'][0]

    - name: Uncordon node after upgrade
      command: kubectl uncordon {{ inventory_hostname }}
      when: inventory_hostname == groups['spark_kubernetes'][0]
