{
 "title": "Active Batches",
 "time": { "from": "2024-10-06T13:42:00.666Z", "to": "2024-10-06T18:25:41.949Z" },
 "panels": [
  {
   "title": "Active Spark Jobs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "class",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "count",
       "id": "1",
       "settings": {},
       "type": "sum"
      }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Net Page Operations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "docker.container.labels.role",
       "id": "7",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "docker.memory.stats.pgfault", "id": "5", "settings": { "unit": "second" }, "type": "rate" },
      {
       "field": "docker.memory.stats.pgfault",
       "id": "6",
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "_index:metrics-docker.memory-default",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Spark CPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "docker.container.labels.role",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "10s" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "docker.cpu.total.pct", "id": "1", "type": "sum" }
     ],
     "query": "_index:metrics-docker.cpu-default",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Page Faults",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "docker.container.labels.role",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "docker.memory.stats.pgfault", "id": "1", "type": "sum" },
      { "field": "docker.memory.stats.pgpgin", "id": "4", "type": "sum" },
      { "field": "docker.memory.stats.pgpgout", "id": "5", "type": "sum" }
     ],
     "query": "_index:metrics-docker.memory-default",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Net Page Faults",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "docker.memory.stats.pgfault", "id": "1", "type": "sum" }
     ],
     "query": "_index:metrics-docker.memory-default",
     "timeField": "@timestamp"
    },
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "sum" }
     ],
     "query": "_index:metrics-docker.memory-default",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Network Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "docker.container.labels.role",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "10s" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "docker.network.inbound.bytes", "id": "1", "type": "sum" },
      { "field": "docker.network.outbound.bytes", "id": "4", "settings": { "script": "_value*-1" }, "type": "sum" },
      { "id": "5", "type": "count" }
     ],
     "query": "_index:metrics-docker.network-default",
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}