{
 "title": "Active Batches2",
 "time": { "from": "2024-10-06T15:09:45.833Z", "to": "2024-10-06T15:29:50.555Z" },
 "panels": [
  {
   "title": "Active Spark Jobs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "class",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "count",
       "id": "1",
       "settings": {},
       "type": "sum"
      }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Network Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "docker.container.labels.role",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "10s" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "docker.network.inbound.bytes", "id": "1", "type": "sum" },
      { "field": "docker.network.outbound.bytes", "id": "4", "settings": { "script": "_value*-1" }, "type": "sum" },
      { "id": "5", "type": "count" }
     ],
     "query": "_index:metrics-docker.network-default",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Spark CPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "docker.container.labels.role",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "10s" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "docker.cpu.total.pct", "id": "1", "type": "sum" }
     ],
     "query": "_index:metrics-docker.cpu-default",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Page Faults",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "docker.container.labels.role",
       "id": "3",
       "settings": { "min_doc_count": "3", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": "1" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "docker.memory.stats.pgfault", "id": "1", "type": "sum" },
      { "field": "docker.memory.stats.pgpgin", "id": "4", "type": "sum" },
      { "field": "docker.memory.stats.pgpgout", "id": "5", "type": "sum" }
     ],
     "query": "_index:metrics-docker.memory-default",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Network Byte Rates",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": "1" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "docker.network.inbound.bytes", "id": "1", "type": "avg" },
      { "field": "docker.network.outbound.bytes", "id": "3", "settings": { "script": "_value*-1" }, "type": "avg" }
     ],
     "query": "_index:  metrics-docker.network-default AND docker.container.labels.role:\"Spark Worker\"  ",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Page Faults",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "docker.container.labels.role",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": "1" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "docker.memory.stats.pgmajfault", "id": "1", "type": "avg" }
     ],
     "query": "_index:metrics-docker.memory-default",
     "timeField": "@timestamp"
    },
    {
     "bucketAggs": [
      {
       "field": "docker.container.labels.role",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": "1" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "docker.memory.stats.pgfault", "id": "1", "type": "avg" }
     ],
     "query": "_index:metrics-docker.memory-default",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Page Fault Rates",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": "1" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "docker.memory.stats.pgfault", "id": "3", "type": "avg" }
     ],
     "query": "_index:metrics-docker.memory-default AND docker.container.labels.role:\"Spark Worker\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Network Byte Rates",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "docker.network.inbound.bytes", "id": "1", "type": "avg" },
      { "field": "docker.network.outbound.bytes", "id": "3", "settings": { "script": "_value*-1" }, "type": "avg" }
     ],
     "query": "_index:  metrics-docker.network-default AND docker.container.labels.role:\"Spark Worker\"  ",
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}