---
- name: Mount Spark Events Directory
  hosts: kubernetes_master:kubernetes_workers
  become: true
  vars_files:
    - "{{ playbook_dir | dirname | dirname }}/vars/nfs_vars.yml"
  vars:
    nfs_server: "{{ groups['nfs_servers'][0] }}"
    spark_events_export: "{{ NFS_SPARK_EVENTS_EXPORT }}"
    spark_events_mount: "{{ SPARK_EVENTS_MOUNT }}"
  tasks:
    - name: Create Spark events mount point
      file:
        path: "{{ spark_events_mount }}"
        state: directory
        mode: '0777'

    - name: Mount Spark events NFS share
      mount:
        path: "{{ spark_events_mount }}"
        src: "{{ nfs_server }}:{{ spark_events_export }}"
        fstype: nfs
        opts: rw,sync
        state: mounted
