{
 "title": "Spark Cluster Metrics",
 "tags": [
  "spark",
  "system",
  "metrics"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "log_levels", "label": "Log Levels", "query": "ERROR,WARN,INFO,DEBUG,TRACE" }
  ]
 },
 "panels": [
  {
   "title": "Active Spark Jobs (Avg, excl Tasks)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "bucketAggs": [
      {
       "id": "1",
       "type": "terms",
       "field": "class",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "0" }
      },
      { "id": "2", "type": "date_histogram", "field": "@timestamp", "settings": { "interval": "auto", "min_doc_count": "0" } }
     ],
     "metrics": [
      { "id": "1", "type": "avg", "field": "count" }
     ],
     "query": "_index:batch-metrics-ds AND NOT class:\"Task\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Host CPU Utilization %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent(0-100)" } },
   "yaxes": [
    { "format": "percent", "label": "CPU %" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "host.name",
       "id": "1",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "$__interval" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "system.cpu.total.pct", "id": "1", "type": "avg" }
     ],
     "query": "_index:metrics-system.cpu-default",
     "timeField": "@timestamp",
     "alias": "{{host.name}} CPU"
    }
   ]
  },
  {
   "title": "Network Byte Rate (In/Out)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "yaxes": [
    { "format": "Bps", "label": "Bytes/sec" }
   ],
   "targets": [
    {
     "query": "_index:metrics-system.network-default AND system.network.name:(enp* OR ens* OR eth0 OR eth1) AND NOT system.network.name:lo",
     "alias": "{{term host.name}} In",
     "metrics": [
      {
       "id": "1",
       "type": "max",
       "field": "system.network.in.bytes",
       "hide": true
      },
      {
       "id": "2",
       "type": "derivative",
       "field": "1",
       "pipelineAgg": "1",
       "settings": { "unit": "$__interval" },
       "hide": true
      },
      {
       "id": "3",
       "type": "bucket_script",
       "pipelineAgg": "2",
       "settings": { "script": "params._value * -1" },
       "pipelineVariables": [
        { "name": "_value", "pipelineAgg": "2" }
       ]
      }
     ],
     "bucketAggs": [
      {
       "id": "4",
       "type": "terms",
       "field": "host.name",
       "settings": { "min_doc_count": "1", "order": "asc", "orderBy": "_key", "size": "10" }
      },
      { "id": "5", "type": "date_histogram", "field": "@timestamp", "settings": { "interval": "$__interval" } }
     ],
     "timeField": "@timestamp"
    },
    {
     "query": "_index:metrics-system.network-default AND system.network.name:(enp* OR ens* OR eth0 OR eth1) AND NOT system.network.name:lo",
     "alias": "{{term host.name}} Out",
     "metrics": [
      {
       "id": "1",
       "type": "max",
       "field": "system.network.out.bytes",
       "hide": true
      },
      {
       "id": "2",
       "type": "derivative",
       "field": "1",
       "pipelineAgg": "1",
       "settings": { "unit": "$__interval" }
      }
     ],
     "bucketAggs": [
      {
       "id": "3",
       "type": "terms",
       "field": "host.name",
       "settings": { "min_doc_count": "1", "order": "asc", "orderBy": "_key", "size": "10" }
      },
      { "id": "4", "type": "date_histogram", "field": "@timestamp", "settings": { "interval": "$__interval" } }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Disk I/O Rate (Read/Write)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "yaxes": [
    { "format": "Bps", "label": "Bytes/sec" }
   ],
   "targets": [
    {
     "query": "_index:metrics-system.diskio-default",
     "alias": "{{term host.name}} Read",
     "metrics": [
      {
       "id": "1",
       "type": "max",
       "field": "system.diskio.read.bytes",
       "hide": true
      },
      {
       "id": "2",
       "type": "derivative",
       "field": "1",
       "pipelineAgg": "1",
       "settings": { "unit": "$__interval" },
       "hide": true
      },
      {
       "id": "3",
       "type": "bucket_script",
       "pipelineAgg": "2",
       "settings": { "script": "params._value * -1" },
       "pipelineVariables": [
        { "name": "_value", "pipelineAgg": "2" }
       ]
      }
     ],
     "bucketAggs": [
      {
       "id": "4",
       "type": "terms",
       "field": "host.name",
       "settings": { "min_doc_count": "1", "order": "asc", "orderBy": "_key", "size": "10" }
      },
      { "id": "5", "type": "date_histogram", "field": "@timestamp", "settings": { "interval": "$__interval" } }
     ],
     "timeField": "@timestamp"
    },
    {
     "query": "_index:metrics-system.diskio-default",
     "alias": "{{term host.name}} Write",
     "metrics": [
      {
       "id": "1",
       "type": "max",
       "field": "system.diskio.write.bytes",
       "hide": true
      },
      {
       "id": "2",
       "type": "derivative",
       "field": "1",
       "pipelineAgg": "1",
       "settings": { "unit": "$__interval" }
      }
     ],
     "bucketAggs": [
      {
       "id": "3",
       "type": "terms",
       "field": "host.name",
       "settings": { "min_doc_count": "1", "order": "asc", "orderBy": "_key", "size": "10" }
      },
      { "id": "4", "type": "date_histogram", "field": "@timestamp", "settings": { "interval": "$__interval" } }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Loopback Traffic (Internal)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "yaxes": [
    { "format": "Bps", "label": "Bytes/sec" }
   ],
   "targets": [
    {
     "query": "_index:metrics-system.network-default AND system.network.name:lo",
     "alias": "{{term host.name}} In",
     "metrics": [
      {
       "id": "1",
       "type": "max",
       "field": "system.network.in.bytes",
       "hide": true
      },
      {
       "id": "2",
       "type": "derivative",
       "field": "1",
       "pipelineAgg": "1",
       "settings": { "unit": "$__interval" },
       "hide": true
      },
      {
       "id": "3",
       "type": "bucket_script",
       "pipelineAgg": "2",
       "settings": { "script": "params._value * -1" },
       "pipelineVariables": [
        { "name": "_value", "pipelineAgg": "2" }
       ]
      }
     ],
     "bucketAggs": [
      {
       "id": "4",
       "type": "terms",
       "field": "host.name",
       "settings": { "min_doc_count": "1", "order": "asc", "orderBy": "_key", "size": "10" }
      },
      { "id": "5", "type": "date_histogram", "field": "@timestamp", "settings": { "interval": "$__interval" } }
     ],
     "timeField": "@timestamp"
    },
    {
     "query": "_index:metrics-system.network-default AND system.network.name:lo",
     "alias": "{{term host.name}} Out",
     "metrics": [
      {
       "id": "1",
       "type": "max",
       "field": "system.network.out.bytes",
       "hide": true
      },
      {
       "id": "2",
       "type": "derivative",
       "field": "1",
       "pipelineAgg": "1",
       "settings": { "unit": "$__interval" }
      }
     ],
     "bucketAggs": [
      {
       "id": "3",
       "type": "terms",
       "field": "host.name",
       "settings": { "min_doc_count": "1", "order": "asc", "orderBy": "_key", "size": "10" }
      },
      { "id": "4", "type": "date_histogram", "field": "@timestamp", "settings": { "interval": "$__interval" } }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "System Load Average",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short", "label": "Load" }
   ],
   "targets": [
    {
     "query": "_index:metrics-system.load-default",
     "metrics": [
      { "id": "1", "type": "avg", "field": "system.load.1" }
     ],
     "bucketAggs": [
      {
       "id": "1",
       "type": "terms",
       "field": "host.name",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" }
      },
      { "id": "2", "type": "date_histogram", "field": "@timestamp", "settings": { "interval": "$__interval" } }
     ],
     "alias": "{{host.name}} Load 1m",
     "timeField": "@timestamp"
    },
    {
     "query": "_index:metrics-system.load-default",
     "metrics": [
      { "id": "1", "type": "avg", "field": "system.load.5" }
     ],
     "bucketAggs": [
      {
       "id": "1",
       "type": "terms",
       "field": "host.name",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" }
      },
      { "id": "2", "type": "date_histogram", "field": "@timestamp", "settings": { "interval": "$__interval" } }
     ],
     "alias": "{{host.name}} Load 5m",
     "timeField": "@timestamp"
    },
    {
     "query": "_index:metrics-system.load-default",
     "metrics": [
      { "id": "1", "type": "avg", "field": "system.load.15" }
     ],
     "bucketAggs": [
      {
       "id": "1",
       "type": "terms",
       "field": "host.name",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" }
      },
      { "id": "2", "type": "date_histogram", "field": "@timestamp", "settings": { "interval": "$__interval" } }
     ],
     "alias": "{{host.name}} Load 15m",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Host Memory Utilization %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percent(0-100)" } },
   "yaxes": [
    { "format": "percent", "label": "Memory %" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "host.name",
       "id": "1",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "$__interval" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "system.memory.used.pct", "id": "1", "type": "avg" }
     ],
     "query": "_index:metrics-system.memory-default",
     "timeField": "@timestamp",
     "alias": "{{host.name}} Memory"
    }
   ]
  },
  {
   "title": "Page Fault Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short", "label": "Faults/sec" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "host.name",
       "id": "1",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "$__interval" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "system.memory.page_stats.pgfault.rate",
       "id": "1",
       "type": "avg"
      }
     ],
     "query": "_index:metrics-system.memory-default",
     "timeField": "@timestamp",
     "alias": "{{host.name}} Page Faults"
    },
    {
     "bucketAggs": [
      {
       "field": "host.name",
       "id": "1",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "$__interval" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "system.memory.page_stats.pgmajfault.rate",
       "id": "1",
       "type": "avg"
      }
     ],
     "query": "_index:metrics-system.memory-default",
     "timeField": "@timestamp",
     "alias": "{{host.name}} Major Faults"
    }
   ]
  },
  {
   "title": "GPU Metrics (Utilization & Temperature)",
   "type": "timeseries",
   "description": "Tracks AMD GPU utilization, VRAM usage, and edge temperature across Lab1/Lab2 nodes",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "percent(0-100)" } },
   "targets": [
    {
     "alias": "{{gpu.card}} GPU %",
     "bucketAggs": [
      {
       "field": "gpu.card",
       "id": "1",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "5" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "$__interval" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "gpu.utilization.core_percent", "id": "1", "type": "avg" }
     ],
     "query": "_index:metrics-gpu-default",
     "timeField": "@timestamp"
    },
    {
     "alias": "{{gpu.card}} VRAM %",
     "bucketAggs": [
      {
       "field": "gpu.card",
       "id": "1",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "5" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "$__interval" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "gpu.utilization.memory_percent", "id": "1", "type": "avg" }
     ],
     "query": "_index:metrics-gpu-default",
     "timeField": "@timestamp"
    },
    {
     "alias": "{{gpu.card}} Edge Temp (°C)",
     "bucketAggs": [
      {
       "field": "gpu.card",
       "id": "1",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "5" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "$__interval" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "gpu.temperature_c.edge", "id": "1", "type": "avg" }
     ],
     "query": "_index:metrics-gpu-default",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Spark Application Logs by Level",
   "type": "barchart",
   "description": "Count of Spark application log entries by log level over time",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 40 },
   "targets": [
    {
     "alias": "{{log_level}} - {{hostname}}",
     "bucketAggs": [
      {
       "field": "log_level",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "field": "hostname",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "sum", "field": "log_count" }
     ],
     "query": "_index:metrics-spark-logs-default",
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}