all:
  vars:
    # elastic_agent_version: "8.11.1" 
    # elastic_agent_download_url: "https://artifacts.elastic.co/downloads/beats/elastic-agent/elastic-agent-{{ elastic_agent_version }}-{{ elastic_agent_os }}-{{ elastic_agent_arch }}.{{ elastic_agent_extension }}"
    # elastic_agent_enrollment_url: "http://your-enrollment-url" 
    # elastic_agent_enrollment_token: "your-enrollment-token" 
    ansible_user: ansible
    ansible_connection: ssh
    ansible_ssh_private_key_file: ~/.ssh/id_rsa  # Path to your private key
  children:
    windows:
      vars:
        elastic_agent_os: "windows"
        elastic_agent_arch: "x86_64"
        elastic_agent_extension: "zip"
        # Ansible WinRM configuration for WinRM managed nodes
        # WinRM is no longer in feature development. SSH is the future
        # ansible_connection: winrm  # Overrides global 'ssh' default
        # ansible_winrm_transport: certificate
        # ansible_winrm_server_cert_validation: ignore
        # ansible_winrm_server_cert_validation: validate 
        # ansible_winrm_cert_key_pem: "/home/gxbrooks/.winrm/ansible_client_private_key.pem"
        # ansible_winrm_cert_pem: "/home/gxbrooks/.winrm/ansible_client_cert.pem"
        # ansible_winrm_scheme: https
        # ansible_port: 5986
        # ssh specific configs
        ansible_shell_type: powershell
        # ansible_password: "{{ vaulted_password }}"  # Omit if using keys only
        ansible_python_interpreter: C:\Program Files\Python313\python.exe"
      hosts:
        GaryPC:
          ansible_host: GaryPC.lan
          
        Lab1:
          ansible_host: Lab1.lan
    linux:
      vars:
        elastic_agent_os: "linux"
        elastic_agent_arch: "x86_64"
        elastic_agent_extension: "tar.gz"
        ansible_python_interpreter: "/usr/bin/python3"
        # SSH configuration
        # Managed node communication configuration for ssh managed nodes

      children:
        native:
          vars:
            ansible_port: 22
          hosts:
            Lab2:
              ansible_host: Lab2.lan 
        wsl:
          vars:
            ansible_port: 2222
          hosts:
            GaryPC-WSL:
              ansible_host: GaryPC.lan
            Lab1-WSL:
              ansible_host: Lab1.lan
