

[windows_hosts]
GaryPC ansible_host=garypc \
	ansible_user=Administrator \
	ansible_connection=ssh \
	ansible_port=22
Lab1 ansible_host=Lab1 \
	ansible_user=Administrator \
	ansible_connection=ssh \
	ansible_port=22

[wsl_hosts]
GaryPC_WSL ansible_host=localhost \
	ansible_user=gxbrooks \
	ansible_port=2222 \
	ansible_connection=ssh
Lab1_WSL ansible_host=Lab1 \
	ansible_user=gxbrooks \
	ansible_port=2222 \
	ansible_connection=ssh

[ubuntu_hosts]
Lab2 ansible_host=Lab2 \
	ansible_user=gxbrooks \
	ansible_ssh_private_key_file=/

[all:vars]
ansible_python_interpreter=/usr/bin/python3
elastic_agent_version=8.10.0 # Change to your desired version
elastic_agent_download_url=https://artifacts.elastic.co/downloads/beats/elastic-agent/elastic-agent-${elastic_agent_version}-linux-x86_64.tar.gz
elastic_stack_containers=['elasticsearch', 'kibana', 'logstash', 'your-application-container']