

input {
	beats {
		port => "${SPARK_LS_PORT}"
	}
}

filter {
	json {
		source => "message"
		target => "Spark"
	}
}

output {
	elasticsearch {
		# index => "spark-%{+YYYY.MM.dd}"
		hosts=> "${ELASTIC_HOSTS}"
		user=> "${ELASTIC_USER}"
		password=> "${ELASTIC_PASSWORD}"
		cacert=> "certs/ca/ca.crt"
		data_stream => "true"
		data_stream_type => "logs"			# Can be "logs", "metrics", or "synthetics"
		data_stream_dataset => "sparkds"
		data_stream_namespace => "sparkns"
	}
}
