

input {
	beats {
		port => "${SPARK_LS_PORT}"
	}
}

filter {

	mutate {
		rename => { "[spark][Properties][spark.rdd.scope]" => "[spark.rdd.scope.id]" }
	}
	
	ruby {
		code => '
		  eventName = event.get("[spark][Event]")
		  puts "Filter Debug: Running filter on Event=#{eventName}............"
		  if event.get("[spark][Task Info][Accumulables]")
			puts "Filter Debug: Found Task Info "
			array = event.get("[spark][Task Info][Accumulables]")
			array.each_with_index do |item, index|
			  if item["Value"]
				v = item["Value"].class
			    puts "Filter Task Info Debug: Found Value #{v} XXX"
				event.set("[spark][Task Info][Accumulables][#{index}][Value]", item["Value"].to_i)	
			  end
			  if item["Update"]			  
				v = item["Update"].class
			    puts "Filter Debug Info Debug: Found Update #{v} XXX"
				event.set("[spark][Task Info][Accumulables][#{index}][Update]", item["Update"].to_i)
			  end
			end
		  end
		  if event.get("[spark][Stage Info][Accumulables]")
			puts "Filter Debug: Found Stage Info"
			array = event.get("[spark][Stage Info][Accumulables]")
			array.each_with_index do |item, index|
			  if item["Value"]
				v = item["Value"].class
			    puts "Filter Debug: Found Stage Info Value #{v} XXX"
				event.set("[spark][Stage Info][Accumulables][#{index}][Value]", item["Value"].to_i)	
			  end
			  if item["Update"]
				v = item["Update"].class
			    puts "Filter Debug: Found Stage Info Update" #{v} XXX"
				event.set("[spark][Stage Info][Accumulables][#{index}][Update]", item["Update"].to_i)
			  end
			end
		  end
		'
  }
}

output {
	elasticsearch {
		# index => "spark-%{+yyyy.MM.dd}"
		hosts => "${ELASTIC_HOSTS}"
		user => "${ELASTIC_USER}"
		password => "${ELASTIC_PASSWORD}"
		cacert => "certs/ca/ca.crt"
		data_stream => "true"
		# Can be "logs", "metrics", or "synthetics"
		data_stream_type => "logs"                      
		data_stream_dataset => "spark"
		data_stream_namespace => "spark"
	}
}
