apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app":"otel-collector"},"name":"otel-collector-nodeport","namespace":"observability"},"spec":{"ports":[{"name":"otlp-grpc","nodePort":31317,"port":4317,"protocol":"TCP","targetPort":4317},{"name":"otlp-http","nodePort":31318,"port":4318,"protocol":"TCP","targetPort":4318}],"selector":{"app":"otel-collector"},"type":"NodePort"}}
  creationTimestamp: "2025-10-18T01:58:27Z"
  labels:
    app: otel-collector
  name: otel-collector-nodeport
  namespace: observability
  resourceVersion: "2293534"
  uid: 038aa44e-c141-4db1-b59d-9b1b6714162d
spec:
  clusterIP: 10.101.72.69
  clusterIPs:
  - 10.101.72.69
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: otlp-grpc
    nodePort: 31317
    port: 4317
    protocol: TCP
    targetPort: 4317
  - name: otlp-http
    nodePort: 31318
    port: 4318
    protocol: TCP
    targetPort: 4318
  selector:
    app: otel-collector
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
