---
# stop_k8s.yml - Stops Kubernetes services

- name: Stop Kubernetes services
  hosts: spark_kubernetes:&linux
  become: true
  tasks:
    - name: Stop kubelet service
      systemd:
        name: kubelet
        state: stopped
      ignore_errors: yes
      
    - name: Stop containerd service
      systemd:
        name: containerd
        state: stopped
      ignore_errors: yes
